apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: saikrishnapipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: saikrishnapipelinesjavascriptdocker 
    spec:
      containers:
        - name: saikrishnapipelinesjavascriptdocker 
          image: snpregistry001.azurecr.io/saikrishnapipelinesjavascriptdocker
          ports:
          - containerPort: 8080